<?php

/**
 * Generate Dice function-view
 */

declare(strict_types=1);

$header = $header ?? null;
$message = $message ?? null;

$die = new \johl20\Dice\Dice();
$die->roll();

$game21 = new \johl20\Dice\Game21();
$game21->roll();

$game212 = new \johl20\Dice\Game21();
$game212->roll2();

$url =  "//{$_SERVER['HTTP_HOST']}{$_SERVER['REQUEST_URI']}";

$escaped_url = htmlspecialchars( $url, ENT_QUOTES, 'UTF-8' );

?><h1><?= $header ?></h1>

<p><?= $message ?></p>
<!-- Form to send values of dice to next "roll" -->
<form method="post" action="game21post">
<p class="dice-utf8">
<input type="checkbox" id="dice1" name="dice1" value="<?= $game21->getLastRoll() ?>">
<label for="dice1">
<!-- display a graphical die with same value as generated by getlastroll -->
<i class="dice-<?= $game21->getLastRoll() ?>"></i>
</label>
<input type="checkbox" id="dice2" name="dice2" value="<?= $game212->getLastRoll2() ?>">
<label for="dice2">
<i class="dice-<?= $game212->getLastRoll2() ?>"></i>
</label>
<input type="submit" value="Roll Dice">
</form>
<h2>Sum:</h2>
<h2><?= $game21->getLastRoll() + $game212->getLastRoll2() ?></h2>
